name: Build and Push Docker Image with DinD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    services:
      docker:
        image: docker:19.03.12
        options: --privileged # DinD requires privileged mode

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set up Docker CLI inside the Docker service container
      - name: Set up Docker
        run: |
          docker version

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitimage:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/gitimage:latest
