name: Build, Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: docker-runner  # Ensure you have a self-hosted runner with Docker installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitimage:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gitimage:latest
  deploy:
    needs: build  
    runs-on: kube-master  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Update Kubernetes Deployment with new Docker image
        run: |
          kubectl delete deploy --my-app
          kubectl create deploy my-app --image sahiljangra/gitimage:latest --replicas 2
  
