name: Build, Push Docker Image, and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: self-hosted  # Ensure you have a self-hosted runner with Docker installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitimage:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gitimage:latest

  deploy:
    needs: build  # Ensures the 'deploy' job runs after the 'build' job is complete
    runs-on: kube-master  # Assuming a self-hosted runner named kube-master

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for Docker image to be available
        run: sleep 60  # Reduce waiting time; Docker Hub push should be relatively fast

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes Deployment with new Docker image
        run: |
          kubectl set image deployment/my-app my-app-container=${{ secrets.DOCKER_USERNAME }}/gitimage:latest
          kubectl rollout status deployment/my-app
